apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: hipster-shop
spec:
  selector:
    matchLabels:
      app: paymentservice
      product: hipster-shop
  template:
    metadata:
      labels:
        app: paymentservice
        product: hipster-shop
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        # image: gcr.io/google-samples/microservices-demo/paymentservice:v0.2.0
        image: gcr.io/dynatrace-demoability/paymentservice:999999-image-tag-not-on-the-registry
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
